version: "2"
services:
  editor-www:
    image: nginx:stable-alpine
    container_name: isaac-editor
    restart: always
    volumes:
      - "./app:/usr/share/nginx/html"
networks:
  default:
    external:
      name: isaac    
