version: "2"
services:
  editor-www:
    image: nginx:stable-alpine
    container_name: isaac-editor
    restart: always
    volumes:
      - "/local/data/editor-github-auth-config.js:/usr/share/nginx/html/js/lib/github/github_application.js:ro"
      - "./app:/usr/share/nginx/html"
networks:
  default:
    external:
      name: isaac    
